module.exports = [
{"name":"머리카락 칠하는 법","link":"https://youtube.com/watch?v=SB8j2UKoYVM?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"머리카락 그리는 법","link":"https://youtube.com/watch?v=4fCWuhYkWLA?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"눈 그리는 법","link":"https://youtube.com/watch?v=2zSeiHZvdq8?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"눈동자 그리는 법","link":"https://youtube.com/watch?v=dTj9h_TKo3E?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"손 그리는 법","link":"https://youtube.com/watch?v=HOuc7WL0L5U?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"캐릭터 비율 그리는 법","link":"https://youtube.com/watch?v=NwNx-LVSCLI?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"에스디 캐릭터 비율 그리는 법","link":"https://youtube.com/watch?v=LMfRbYYqzDc?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"집중선 만드는 법","link":"https://youtube.com/watch?v=-DaAP5y6v2w?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"웃는 표정 그리는 법","link":"https://youtube.com/watch?v=eRlg48nQXuE?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"우는 표정 그리는 법","link":"https://youtube.com/watch?v=No7-GaFMbmw?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"운동화 그리는 법","link":"https://youtube.com/watch?v=wSv04sJZiYY?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"구두 그리는 법","link":"https://youtube.com/watch?v=JDqN-kN3QJc?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":" 체크무늬 치마를 칠하는 법","link":"https://youtube.com/watch?v=Cyf_P0Idh1w?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"앞머리 그리는 법","link":"https://youtube.com/watch?v=iN0w-Nx-cpA?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"리본 그리는 법","link":"https://youtube.com/watch?v=l2AnnT7ZfXw?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"옷주름 그리는 법","link":"https://youtube.com/watch?v=YuZ-474mGM8?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"곰인형 그리는 법","link":"https://youtube.com/watch?v=Hy-1Wt50qZg?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"옷주름 그리는 법","link":"https://youtube.com/watch?v=wDevXQmRII0?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"눈동차 칠하는 법","link":"https://youtube.com/watch?v=TAl87OzdWN8?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"생머리 그리는 법","link":"https://youtube.com/watch?v=ARQUq2XkR-M?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"옆모습 그리는 법","link":"https://youtube.com/watch?v=Wtgl7N4fZwQ?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"남자 올림머리 그리는 법","link":"https://youtube.com/watch?v=Q73ayx7Bcvw?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"포니테일 그리는 법","link":"https://youtube.com/watch?v=gKznlptx8tU?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"트윈테일 그리는 법","link":"https://youtube.com/watch?v=gKznlptx8tU?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"땋은머리 그리는 법","link":"https://youtube.com/watch?v=uBkvvs-s38o?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"올림머리 그리는 법","link":"https://youtube.com/watch?v=UQLTuc-6Sx0?list=PLmrVWPFHf_oGpvuhKmwuaJ4U5bE5LnH6g"},
{"name":"그림 기초","link":"https://youtube.com/watch?v=8So8YgN1uUU?list=PLs_xf3L3jWLF7FBB0KjlUvlPdc5XGH-7V"},
{"name":"빛과 명함","link":"https://youtube.com/watch?v=_2s4ydT7bN0?list=PLs_xf3L3jWLF7FBB0KjlUvlPdc5XGH-7V"},
{"name":"빛과 색","link":"https://youtube.com/watch?v=MVx-8hi6bck?list=PLs_xf3L3jWLF7FBB0KjlUvlPdc5XGH-7V"},
{"name":"원근법","link":"https://youtube.com/watch?v=CwOrE39ePrw?list=PLs_xf3L3jWLF7FBB0KjlUvlPdc5XGH-7V"},
{"name":"투시도법","link":"https://youtube.com/watch?v=CwOrE39ePrw?list=PLs_xf3L3jWLF7FBB0KjlUvlPdc5XGH-7V"},
{"name":"공기원근법","link":"https://youtube.com/watch?v=a7KDIWeFf2w?list=PLs_xf3L3jWLF7FBB0KjlUvlPdc5XGH-7V"},
{"name":"인체 그리는 법","link":"https://youtube.com/watch?v=36eE_19OhGU?list=PLs_xf3L3jWLF7FBB0KjlUvlPdc5XGH-7V"},
{"name":"인물화 그리는 법","link":"https://youtube.com/watch?v=jIVd3AOhJvg?list=PLs_xf3L3jWLF7FBB0KjlUvlPdc5XGH-7V"}
]



